# Generated by Django 3.1.6 on 2021-02-16 18:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='html',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock())], default=""),
            preserve_default=False,
        ),
    ]
