# Generated by Django 3.1.6 on 2021-02-17 11:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210217_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='html',
            field=wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock(blank=True, required=False))]),
        ),
    ]
